```sql
-- =============================================================================
-- Transactional Payments Ledger — Complete Database Schema
-- PostgreSQL 16
--
-- Migration structure (Flyway):
--   V1__initial_schema.sql  — all CREATE TABLE statements with constraints
--   V2__indexes.sql         — all CREATE INDEX statements
--
-- Design notes:
--   • All monetary amounts stored as BIGINT in minor currency units (e.g. cents).
--     This eliminates floating-point rounding errors entirely.
--   • All primary keys are UUID generated by gen_random_uuid() to avoid
--     sequential-scan hotspots on inserts and to prevent enumeration attacks.
--   • TIMESTAMPTZ (timestamp with time zone) is used throughout so that all
--     timestamps are stored in UTC and are unambiguous across time zones.
--   • ledger_entries has no UPDATE or DELETE path. Immutability is enforced at
--     the application layer (repositories issue no UPDATE/DELETE against this
--     table) and documented here for operators. A trigger is added as a
--     defence-in-depth guard.
--   • The zero-sum invariant (Σ amount_minor × direction_sign = 0 across all
--     ledger_entries) is enforced by the application's TransferService, verified
--     continuously by ReconciliationService, and supported by the covering index
--     idx_ledger_entries_reconciliation.
--   • Row-level locking for the pessimistic concurrency strategy relies on
--     SELECT … FOR UPDATE on the accounts table. Accounts are always locked in
--     ascending UUID order to prevent deadlocks.
--   • The optimistic concurrency strategy uses the accounts.version column:
--     UPDATE accounts SET … WHERE id = ? AND version = <read_version>.
--     A mismatch (0 rows updated) signals a concurrent modification.
--   • CHECK constraints on accounts.balance >= accounts.min_balance provide a
--     last-resort database-level guard against negative-balance bugs.
-- =============================================================================


-- =============================================================================
-- V1__initial_schema.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- accounts
--
-- Represents a ledger account. The balance column is a materialized cache of
-- the sum of all ledger_entries for this account; it is kept in sync by
-- TransferService within the same ACID transaction that writes ledger_entries.
-- The authoritative balance is always derivable from ledger_entries alone.
--
-- Columns:
--   id           — surrogate primary key (UUID v4)
--   name         — human-readable account label; not required to be unique
--   currency     — ISO 4217 three-letter currency code (e.g. 'USD', 'EUR')
--   min_balance  — floor below which balance may not fall; >= 0 always
--   balance      — materialized running balance in minor currency units
--   version      — monotonically increasing integer used by the optimistic
--                  concurrency strategy; incremented on every balance update
--   created_at   — wall-clock time of row creation (UTC)
--   updated_at   — wall-clock time of last modification (UTC)
--
-- Constraints:
--   accounts_balance_gte_min   — balance may never fall below min_balance;
--                                PostgreSQL evaluates this at statement end,
--                                so intermediate states within a transaction
--                                are permitted as long as the final state
--                                satisfies the constraint
--   accounts_min_balance_gte_zero — min_balance must be non-negative
--   accounts_currency_format   — currency must be exactly 3 uppercase letters
--   accounts_version_gte_zero  — version must be non-negative
--   accounts_balance_not_null  — enforced by NOT NULL (belt-and-suspenders
--                                comment; already implied by column definition)
-- ---------------------------------------------------------------------------
CREATE TABLE accounts (
    id           UUID         NOT NULL DEFAULT gen_random_uuid(),
    name         VARCHAR(255) NOT NULL,
    currency     CHAR(3)      NOT NULL DEFAULT 'USD',
    min_balance  BIGINT       NOT NULL DEFAULT 0,
    balance      BIGINT       NOT NULL DEFAULT 0,
    version      BIGINT       NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT accounts_pkey
        PRIMARY KEY (id),

    CONSTRAINT accounts_balance_gte_min
        CHECK (balance >= min_balance),

    CONSTRAINT accounts_min_balance_gte_zero
        CHECK (min_balance >= 0),

    CONSTRAINT accounts_currency_format
        CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT accounts_version_gte_zero
        CHECK (version >= 0)
);

COMMENT ON TABLE  accounts                IS 'Ledger accounts. Balance is a materialized cache; authoritative balance is derived from ledger_entries.';
COMMENT ON COLUMN accounts.id            IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN accounts.name          IS 'Human-readable account label.';
COMMENT ON COLUMN accounts.currency      IS 'ISO 4217 three-letter currency code.';
COMMENT ON COLUMN accounts.min_balance   IS 'Minimum allowed balance in minor currency units. Must be >= 0.';
COMMENT ON COLUMN accounts.balance       IS 'Materialized running balance in minor currency units. Must be >= min_balance.';
COMMENT ON COLUMN accounts.version       IS 'Optimistic concurrency version counter. Incremented on every balance update.';
COMMENT ON COLUMN accounts.created_at    IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN accounts.updated_at    IS 'Row last-modified timestamp (UTC).';


-- ---------------------------------------------------------------------------
-- transfers
--
-- Represents a single transfer request. A transfer record is created before
-- ledger_entries are written (status = PENDING) and updated to COMPLETED or
-- FAILED atomically within the same transaction. The idempotency_key column
-- links this record to the idempotency_keys table for audit purposes; the
-- uniqueness constraint here is a secondary guard (the primary uniqueness
-- enforcement is on idempotency_keys.key).
--
-- Columns:
--   id               — surrogate primary key (UUID v4)
--   idempotency_key  — the client-supplied Idempotency-Key header value;
--                      nullable because saga sub-steps may not carry one
--   from_account_id  — the account being debited; FK to accounts
--   to_account_id    — the account being credited; FK to accounts
--   amount_minor     — transfer amount in minor currency units; must be > 0
--   currency         — ISO 4217 code; must match both accounts' currency
--   status           — lifecycle state: PENDING → COMPLETED | FAILED
--   created_at       — wall-clock time of row creation (UTC)
--   updated_at       — wall-clock time of last modification (UTC)
--
-- Constraints:
--   transfers_status_valid        — status must be one of the defined values
--   transfers_amount_positive     — amount must be strictly positive
--   transfers_currency_format     — currency must be 3 uppercase letters
--   transfers_different_accounts  — from and to accounts must differ
--   transfers_idempotency_key_uq  — idempotency_key is unique when present
-- ---------------------------------------------------------------------------
CREATE TABLE transfers (
    id               UUID         NOT NULL DEFAULT gen_random_uuid(),
    idempotency_key  VARCHAR(255),
    from_account_id  UUID         NOT NULL,
    to_account_id    UUID         NOT NULL,
    amount_minor     BIGINT       NOT NULL,
    currency         CHAR(3)      NOT NULL,
    status           VARCHAR(50)  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT transfers_pkey
        PRIMARY KEY (id),

    CONSTRAINT transfers_from_account_fk
        FOREIGN KEY (from_account_id) REFERENCES accounts (id),

    CONSTRAINT transfers_to_account_fk
        FOREIGN KEY (to_account_id) REFERENCES accounts (id),

    CONSTRAINT transfers_status_valid
        CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),

    CONSTRAINT transfers_amount_positive
        CHECK (amount_minor > 0),

    CONSTRAINT transfers_currency_format
        CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT transfers_different_accounts
        CHECK (from_account_id <> to_account_id),

    CONSTRAINT transfers_idempotency_key_uq
        UNIQUE (idempotency_key)
);

COMMENT ON TABLE  transfers                   IS 'Transfer requests. One row per client request. Ledger entries are the authoritative record; this table provides status tracking and idempotency linkage.';
COMMENT ON COLUMN transfers.id               IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN transfers.idempotency_key  IS 'Client-supplied Idempotency-Key header value. NULL for saga sub-steps.';
COMMENT ON COLUMN transfers.from_account_id  IS 'Account being debited. FK to accounts.';
COMMENT ON COLUMN transfers.to_account_id    IS 'Account being credited. FK to accounts.';
COMMENT ON COLUMN transfers.amount_minor     IS 'Transfer amount in minor currency units. Must be > 0.';
COMMENT ON COLUMN transfers.currency         IS 'ISO 4217 currency code. Must match both accounts.';
COMMENT ON COLUMN transfers.status           IS 'Lifecycle state: PENDING → COMPLETED | FAILED.';
COMMENT ON COLUMN transfers.created_at       IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN transfers.updated_at       IS 'Row last-modified timestamp (UTC).';


-- ---------------------------------------------------------------------------
-- ledger_entries
--
-- The append-only, immutable double-entry bookkeeping log. Every transfer
-- produces exactly two rows: one DEBIT and one CREDIT of equal amount_minor,
-- ensuring the zero-sum invariant holds. No UPDATE or DELETE is ever issued
-- against this table by the application. A trigger (below) enforces this at
-- the database level as a defence-in-depth measure.
--
-- The zero-sum invariant:
--   Σ (CASE WHEN direction='DEBIT'  THEN -amount_minor
--           WHEN direction='CREDIT' THEN  amount_minor END)
--   = 0   across ALL rows at ALL times.
--
-- Columns:
--   id           — surrogate primary key (UUID v4)
--   transfer_id  — the transfer that produced this entry; FK to transfers
--   account_id   — the account affected; FK to accounts
--   direction    — DEBIT (money leaving account) or CREDIT (money entering)
--   amount_minor — absolute amount in minor currency units; always > 0
--   created_at   — wall-clock time of row creation (UTC); no updated_at
--                  because rows are immutable
--
-- Constraints:
--   ledger_entries_direction_valid   — direction must be DEBIT or CREDIT
--   ledger_entries_amount_positive   — amount must be strictly positive
--
-- Immutability trigger: ledger_entries_immutable_tg (defined below)
-- ---------------------------------------------------------------------------
CREATE TABLE ledger_entries (
    id           UUID        NOT NULL DEFAULT gen_random_uuid(),
    transfer_id  UUID        NOT NULL,
    account_id   UUID        NOT NULL,
    direction    VARCHAR(6)  NOT NULL,
    amount_minor BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ledger_entries_pkey
        PRIMARY KEY (id),

    CONSTRAINT ledger_entries_transfer_fk
        FOREIGN KEY (transfer_id) REFERENCES transfers (id),

    CONSTRAINT ledger_entries_account_fk
        FOREIGN KEY (account_id) REFERENCES accounts (id),

    CONSTRAINT ledger_entries_direction_valid
        CHECK (direction IN ('DEBIT', 'CREDIT')),

    CONSTRAINT ledger_entries_amount_positive
        CHECK (amount_minor > 0)
);

COMMENT ON TABLE  ledger_entries              IS 'Append-only double-entry bookkeeping log. IMMUTABLE: no UPDATE or DELETE permitted. Every transfer produces exactly one DEBIT and one CREDIT row of equal amount_minor.';
COMMENT ON COLUMN ledger_entries.id          IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN ledger_entries.transfer_id IS 'The transfer that produced this entry. FK to transfers.';
COMMENT ON COLUMN ledger_entries.account_id  IS 'The account affected by this entry. FK to accounts.';
COMMENT ON COLUMN ledger_entries.direction   IS 'DEBIT = money leaving account; CREDIT = money entering account.';
COMMENT ON COLUMN ledger_entries.amount_minor IS 'Absolute amount in minor currency units. Always > 0. Sign is encoded in direction.';
COMMENT ON COLUMN ledger_entries.created_at  IS 'Row creation timestamp (UTC). No updated_at: rows are immutable.';

-- Defence-in-depth: prevent any UPDATE or DELETE on ledger_entries at the
-- database level, regardless of which application user or tool issues the
-- statement. This fires BEFORE the operation so it can raise an exception
-- without leaving a partial change.
CREATE OR REPLACE FUNCTION ledger_entries_immutability_guard()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'ledger_entries is append-only: UPDATE and DELETE are not permitted. '
        'operation=% entry_id=%',
        TG_OP,
        COALESCE(OLD.id::TEXT, '(unknown)');
END;
$$;

COMMENT ON FUNCTION ledger_entries_immutability_guard() IS
    'Trigger function that unconditionally raises an exception on any attempt '
    'to UPDATE or DELETE a ledger_entries row. Enforces append-only semantics '
    'at the database level as a defence-in-depth measure.';

CREATE TRIGGER ledger_entries_immutable_tg
    BEFORE UPDATE OR DELETE ON ledger_entries
    FOR EACH ROW
    EXECUTE FUNCTION ledger_entries_immutability_guard();

COMMENT ON TRIGGER ledger_entries_immutable_tg ON ledger_entries IS
    'Prevents UPDATE and DELETE on ledger_entries. Fires BEFORE the operation '
    'so no partial change is written. Part of the zero-sum invariant defence.';


-- ---------------------------------------------------------------------------
-- idempotency_keys
--
-- Stores the state and result of every mutating HTTP request that carries an
-- Idempotency-Key header. The primary key on key provides the unique
-- constraint that serializes concurrent duplicate requests: only one INSERT
-- can succeed; the loser receives a unique-constraint violation and falls into
-- the polling loop.
--
-- Columns:
--   key                 — the client-supplied Idempotency-Key header value;
--                         primary key; VARCHAR(255) to accommodate UUIDs,
--                         ULIDs, and arbitrary client-generated strings
--   request_fingerprint — SHA-256 hex digest of the raw request body bytes;
--                         used to detect key reuse with a different body
--   response_snapshot   — the serialized JSON response body stored after
--                         successful execution; replayed verbatim on retry
--   status              — IN_PROGRESS (executing), COMPLETED, FAILED
--   created_at          — wall-clock time of first request (UTC)
--   updated_at          — wall-clock time of last status change (UTC)
--
-- Constraints:
--   idempotency_keys_status_valid — status must be one of the defined values
--   idempotency_keys_fingerprint_len — SHA-256 hex is exactly 64 characters
-- ---------------------------------------------------------------------------
CREATE TABLE idempotency_keys (
    key                 VARCHAR(255) NOT NULL,
    request_fingerprint CHAR(64)     NOT NULL,
    response_snapshot   TEXT,
    status              VARCHAR(20)  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT idempotency_keys_pkey
        PRIMARY KEY (key),

    CONSTRAINT idempotency_keys_status_valid
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')),

    CONSTRAINT idempotency_keys_fingerprint_len
        CHECK (length(request_fingerprint) = 64)
);

COMMENT ON TABLE  idempotency_keys                      IS 'Idempotency gate. One row per unique Idempotency-Key header value. The PRIMARY KEY unique constraint serializes concurrent duplicate requests.';
COMMENT ON COLUMN idempotency_keys.key                 IS 'Client-supplied Idempotency-Key header value. Primary key.';
COMMENT ON COLUMN idempotency_keys.request_fingerprint IS 'SHA-256 hex digest of the raw request body. Used to detect key reuse with a different payload.';
COMMENT ON COLUMN idempotency_keys.response_snapshot   IS 'Serialized JSON response body. NULL while IN_PROGRESS. Replayed verbatim on retry once COMPLETED.';
COMMENT ON COLUMN idempotency_keys.status              IS 'IN_PROGRESS = executing; COMPLETED = response stored; FAILED = execution failed, retry permitted.';
COMMENT ON COLUMN idempotency_keys.created_at          IS 'Timestamp of first request (UTC).';
COMMENT ON COLUMN idempotency_keys.updated_at          IS 'Timestamp of last status change (UTC).';


-- ---------------------------------------------------------------------------
-- sagas
--
-- Tracks the lifecycle of a multi-step saga. One row per saga execution.
-- The orchestrator persists state here before each step so that
-- SagaRecoveryRunner can resume or compensate in-progress sagas after a
-- crash.
--
-- Columns:
--   id            — surrogate primary key (UUID v4)
--   type          — application-defined saga type identifier (e.g.
--                   'MULTI_LEG_TRANSFER'); used by SagaRecoveryRunner to
--                   reconstruct the SagaDefinition
--   state         — lifecycle state (see constraint below)
--   current_step  — zero-based index of the step most recently started;
--                   used by recovery to determine compensation boundary
--   payload       — JSONB blob carrying the saga's input parameters;
--                   stored at creation and read by recovery to reconstruct
--                   step arguments
--   created_at    — wall-clock time of saga creation (UTC)
--   updated_at    — wall-clock time of last state change (UTC)
--
-- State machine:
--   STARTED → COMPLETED          (all steps succeeded)
--   STARTED → COMPENSATING       (a step failed; compensation beginning)
--   COMPENSATING → COMPENSATED   (all compensations succeeded)
--   COMPENSATING → FAILED        (compensation itself failed; manual intervention)
-- ---------------------------------------------------------------------------
CREATE TABLE sagas (
    id           UUID         NOT NULL DEFAULT gen_random_uuid(),
    type         VARCHAR(100) NOT NULL,
    state        VARCHAR(20)  NOT NULL,
    current_step INT          NOT NULL DEFAULT 0,
    payload      JSONB        NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT sagas_pkey
        PRIMARY KEY (id),

    CONSTRAINT sagas_state_valid
        CHECK (state IN ('STARTED', 'COMPLETED', 'COMPENSATING', 'COMPENSATED', 'FAILED')),

    CONSTRAINT sagas_current_step_gte_zero
        CHECK (current_step >= 0)
);

COMMENT ON TABLE  sagas              IS 'Saga lifecycle tracking. One row per saga execution. Persisted before each step to enable crash recovery and compensation.';
COMMENT ON COLUMN sagas.id          IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN sagas.type        IS 'Application-defined saga type identifier. Used by SagaRecoveryRunner to reconstruct the SagaDefinition.';
COMMENT ON COLUMN sagas.state       IS 'STARTED | COMPLETED | COMPENSATING | COMPENSATED | FAILED.';
COMMENT ON COLUMN sagas.current_step IS 'Zero-based index of the step most recently started. Used by recovery to determine compensation boundary.';
COMMENT ON COLUMN sagas.payload     IS 'JSONB input parameters for the saga. Stored at creation; read by recovery to reconstruct step arguments.';
COMMENT ON COLUMN sagas.created_at  IS 'Saga creation timestamp (UTC).';
COMMENT ON COLUMN sagas.updated_at  IS 'Last state-change timestamp (UTC).';


-- ---------------------------------------------------------------------------
-- saga_steps
--
-- Tracks the lifecycle of each individual step within a saga. One row per
-- (saga, step_index) pair. The UNIQUE constraint on (saga_id, step_index)
-- prevents duplicate step records and makes the step log queryable by
-- position.
--
-- Columns:
--   id             — surrogate primary key (UUID v4)
--   saga_id        — the owning saga; FK to sagas
--   step_index     — zero-based position of this step in the saga definition
--   step_type      — application-defined step type identifier (e.g.
--                    'DEBIT_ACCOUNT', 'CREDIT_ACCOUNT', 'RECORD_TRANSFER')
--   state          — lifecycle state (see constraint below)
--   forward_result — JSONB result returned by step.forward(); stored so that
--                    step.compensate() can receive it during recovery
--   created_at     — wall-clock time of row creation (UTC)
--   updated_at     — wall-clock time of last state change (UTC)
--
-- State machine (per step):
--   PENDING → IN_PROGRESS → COMPLETED
--                         → COMPENSATED   (after compensation)
-- ---------------------------------------------------------------------------
CREATE TABLE saga_steps (
    id             UUID         NOT NULL DEFAULT gen_random_uuid(),
    saga_id        UUID         NOT NULL,
    step_index     INT          NOT NULL,
    step_type      VARCHAR(100) NOT NULL,
    state          VARCHAR(20)  NOT NULL,
    forward_result JSONB,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT saga_steps_pkey
        PRIMARY KEY (id),

    CONSTRAINT saga_steps_saga_fk
        FOREIGN KEY (saga_id) REFERENCES sagas (id),

    CONSTRAINT saga_steps_state_valid
        CHECK (state IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'COMPENSATED')),

    CONSTRAINT saga_steps_step_index_gte_zero
        CHECK (step_index >= 0),

    CONSTRAINT saga_steps_saga_step_uq
        UNIQUE (saga_id, step_index)
);

COMMENT ON TABLE  saga_steps                  IS 'Per-step lifecycle tracking within a saga. One row per (saga, step_index). forward_result is stored for use by compensate() during recovery.';
COMMENT ON COLUMN saga_steps.id             IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN saga_steps.saga_id        IS 'Owning saga. FK to sagas.';
COMMENT ON COLUMN saga_steps.step_index     IS 'Zero-based position of this step in the saga definition.';
COMMENT ON COLUMN saga_steps.step_type      IS 'Application-defined step type identifier (e.g. DEBIT_ACCOUNT).';
COMMENT ON COLUMN saga_steps.state          IS 'PENDING | IN_PROGRESS | COMPLETED | COMPENSATED.';
COMMENT ON COLUMN saga_steps.forward_result IS 'JSONB result from step.forward(). Passed to step.compensate() during recovery. NULL until step completes.';
COMMENT ON COLUMN saga_steps.created_at     IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN saga_steps.updated_at     IS 'Last state-change timestamp (UTC).';


-- ---------------------------------------------------------------------------
-- reconciliation_reports
--
-- Stores the output of each ReconciliationService run. One row per
-- scheduled or on-demand reconciliation check. Drift details are stored as
-- JSONB so that the full per-account breakdown is queryable without schema
-- changes.
--
-- Columns:
--   id                — surrogate primary key (UUID v4)
--   run_at            — wall-clock time the check was executed (UTC)
--   global_sum        — Σ(signed amount_minor) across all ledger_entries;
--                       must be 0; any non-zero value indicates corruption
--   drift_detected    — true if global_sum != 0 OR any per-account drift
--   drift_details     — JSONB array of per-account drift records when
--                       drift_detected = true; NULL otherwise
--   accounts_checked  — number of distinct accounts included in the check
--   accounts_drifted  — number of accounts where entry_sum != balance;
--                       must be 0
--
-- Constraints:
--   reconciliation_reports_accounts_checked_gte_zero — sanity check
--   reconciliation_reports_accounts_drifted_gte_zero — sanity check
-- ---------------------------------------------------------------------------
CREATE TABLE reconciliation_reports (
    id               UUID        NOT NULL DEFAULT gen_random_uuid(),
    run_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    global_sum       BIGINT      NOT NULL,
    drift_detected   BOOLEAN     NOT NULL,
    drift_details    JSONB,
    accounts_checked INT         NOT NULL,
    accounts_drifted INT         NOT NULL DEFAULT 0,

    CONSTRAINT reconciliation_reports_pkey
        PRIMARY KEY (id),

    CONSTRAINT reconciliation_reports_accounts_checked_gte_zero
        CHECK (accounts_checked >= 0),

    CONSTRAINT reconciliation_reports_accounts_drifted_gte_zero
        CHECK (accounts_drifted >= 0)
);

COMMENT ON TABLE  reconciliation_reports                   IS 'Output of each ReconciliationService run. One row per check. global_sum must always be 0; any non-zero value indicates a zero-sum invariant violation.';
COMMENT ON COLUMN reconciliation_reports.id               IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN reconciliation_reports.run_at           IS 'Timestamp when the reconciliation check was executed (UTC).';
COMMENT ON COLUMN reconciliation_reports.global_sum       IS 'Σ(signed amount_minor) across all ledger_entries. Must be 0.';
COMMENT ON COLUMN reconciliation_reports.drift_detected   IS 'True if global_sum != 0 or any per-account balance does not match its ledger entry sum.';
COMMENT ON COLUMN reconciliation_reports.drift_details    IS 'JSONB array of per-account drift records. NULL when drift_detected = false.';
COMMENT ON COLUMN reconciliation_reports.accounts_checked IS 'Number of distinct accounts included in this check.';
COMMENT ON COLUMN reconciliation_reports.accounts_drifted IS 'Number of accounts where materialized balance differs from ledger entry sum. Must be 0.';


-- =============================================================================
-- V2__indexes.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- accounts indexes
-- ---------------------------------------------------------------------------

-- Supports ORDER BY id in ConcurrencyStrategy.lockAndLoad() which always
-- locks accounts in ascending UUID order to prevent deadlocks.
-- The PRIMARY KEY index already covers single-row lookups by id; this
-- comment documents that no additional index is needed for that access pattern.

-- Partial index for active accounts if a soft-delete column is added in a
-- future migration. Placeholder comment only; no DDL emitted here.


-- ---------------------------------------------------------------------------
-- transfers indexes
-- ---------------------------------------------------------------------------

-- Lookup by idempotency_key for the idempotency filter and audit queries.
-- Partial: only indexes rows where idempotency_key IS NOT NULL, which is the
-- common case. Saga sub-step transfers with NULL keys are excluded, keeping
-- the index small.
CREATE INDEX idx_transfers_idempotency_key
    ON transfers (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

COMMENT ON INDEX idx_transfers_idempotency_key IS
    'Partial index on transfers.idempotency_key (non-NULL rows only). '
    'Supports idempotency filter lookups and audit queries.';

-- Lookup by from_account_id and to_account_id for account history queries.
CREATE INDEX idx_transfers_from_account_id
    ON transfers (from_account_id);

COMMENT ON INDEX idx_transfers_from_account_id IS
    'Supports account transfer history queries filtered by the debited account.';

CREATE INDEX idx_transfers_to_account_id
    ON transfers (to_account_id);

COMMENT ON INDEX idx_transfers_to_account_id IS
    'Supports account transfer history queries filtered by the credited account.';

-- Lookup by status for monitoring and retry queries.
CREATE INDEX idx_transfers_status
    ON transfers (status)
    WHERE status IN ('PENDING', 'FAILED');

COMMENT ON INDEX idx_transfers_status IS
    'Partial index on transfers.status for PENDING and FAILED rows only. '
    'Supports monitoring queries and failed-transfer retry scans.';


-- ---------------------------------------------------------------------------
-- ledger_entries indexes
-- ---------------------------------------------------------------------------

-- Hot path: per-account balance derivation and reconciliation aggregate.
-- account_id alone supports the JOIN in the reconciliation query.
CREATE INDEX idx_ledger_entries_account_id
    ON ledger_entries (account_id);

COMMENT ON INDEX idx_ledger_entries_account_id IS
    'Supports per-account ledger entry lookups and the reconciliation '
    'JOIN between ledger_entries and accounts.';

-- Hot path: transfer detail lookup (fetch both entries for a given transfer).
CREATE INDEX idx_ledger_entries_transfer_id
    ON ledger_entries (transfer_id);

COMMENT ON INDEX idx_ledger_entries_transfer_id IS
    'Supports fetching all ledger entries for a given transfer_id. '
    'Used by transfer detail endpoints and saga compensation lookups.';

-- Covering index for the reconciliation aggregate query:
--   SELECT account_id,
--          SUM(CASE WHEN direction='DEBIT'  THEN -amount_minor
--                   WHEN direction='CREDIT' THEN  amount_minor END)
--   FROM ledger_entries
--   GROUP BY account_id
-- All three projected columns are in the index, so PostgreSQL can satisfy
-- the query with an index-only scan, avoiding heap fetches on a potentially
-- very large table.
CREATE INDEX idx_ledger_entries_reconciliation
    ON ledger_entries (account_id, direction, amount_minor);

COMMENT ON INDEX idx_ledger_entries_reconciliation IS
    'Covering index for the reconciliation aggregate query. Includes '
    'account_id, direction, and amount_minor so the SUM can be computed '
    'via an index-only scan without touching the heap.';

-- Chronological ordering for audit log queries (most recent entries first).
CREATE INDEX idx_ledger_entries_created_at
    ON ledger_entries (created_at DESC);

COMMENT ON INDEX idx_ledger_entries_created_at IS
    'Supports chronological audit log queries ordered by creation time.';


-- ---------------------------------------------------------------------------
-- idempotency_keys indexes
-- ---------------------------------------------------------------------------

-- The PRIMARY KEY on key already provides the unique index used by the
-- idempotency filter's SELECT … FOR UPDATE. No additional index is needed
-- for the primary lookup path.

-- Index on status to support cleanup jobs that expire old IN_PROGRESS or
-- FAILED keys (future operational tooling).
CREATE INDEX idx_idempotency_keys_status
    ON idempotency_keys (status, updated_at)
    WHERE status IN ('IN_PROGRESS', 'FAILED');

COMMENT ON INDEX idx_idempotency_keys_status IS
    'Partial index on idempotency_keys for IN_PROGRESS and FAILED rows. '
    'Supports the polling loop status check and future cleanup jobs.